spring.application.name=backend

# =========================
# Oracle Database
# =========================
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orclpdb
spring.datasource.username=AI_MOVIE
spring.datasource.password=AiMovie@123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate

# =========================
# JWT
# =========================
app.jwt.secret=${APP_JWT_SECRET}

# =========================
# Logging
# =========================
logging.level.org.springframework.security=DEBUG